#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Syncfusion.EJ2;
    using Vispl.Trainee.CricInfo.ViewScheduledMatches.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MatchSchedule/DisplayMatchDataInGrid.cshtml")]
    public partial class _Views_MatchSchedule_DisplayMatchDataInGrid_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Vispl.Trainee.CricInfo.ViewScheduledMatches.VO.clsMatchScheduleVO>>
    {
        public _Views_MatchSchedule_DisplayMatchDataInGrid_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\MatchSchedule\DisplayMatchDataInGrid.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"form-container\"");

WriteLiteral(">\r\n    <h2>Match List</h2>\r\n    <div");

WriteLiteral(" class=\"grid-data\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 10 "..\..\Views\MatchSchedule\DisplayMatchDataInGrid.cshtml"
   Write(Html.EJS().Grid("Grid").DataSource((IEnumerable<object>)Model).AllowPaging(true).Columns(col =>
           {
               col.Field("FirstTeam").HeaderText("FirstTeam").Width(100).Add();
               col.Field("SecondTeam").HeaderText("SecondTeam").Width(120).Add();
               col.Field("ScheduledTime").HeaderText("ScheduledTime").Format("dd-MM-yyyy HH:mm").Width(120).Add();
               col.Field("Venue").HeaderText("Venue").Width(120).Add();
               col.Field("TournamentName").HeaderText("Tournament").Width(120).Add();
               col.HeaderText("Action").Width("100").Template("#StartTheMatch").Add();
           }).AllowSorting(true).AllowFiltering(true).Height("70%").PageSettings(page => page.PageSize(15)).Render());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/x-template\"");

WriteLiteral(" id=\"StartTheMatch\"");

WriteLiteral(">\r\n    <button class=\"btn-submit\" onclick=\"startMatch(\'${ID}\')\">Toss</button>\r\n</" +
"script>\r\n<script>\r\n    function startMatch(Id) {\r\n        window.location.href =" +
" \'");

            
            #line 27 "..\..\Views\MatchSchedule\DisplayMatchDataInGrid.cshtml"
                           Write(Url.Action("Toss", "MatchSchedule"));

            
            #line default
            #line hidden
WriteLiteral("?Id=\' + Id;\r\n    }\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
